version: '3'
services: 
  golang-redis-pg:
    container_name: golang-redis-pg
    environment:
      GLP_LISTEN_PORT: 9998
      GLP_REDIS_HOST: redis
      GLP_REDIS_PORT: 6379
    image: rms1000watt/golang-redis-pg:latest
    ports:
    - 9998:9998
    depends_on:
    - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
    - 6379:6379
