version: '3'

volumes:
  portainer-data:

services:
  dummy-golang-project:
    container_name: dummy-golang-project
    image: rms1000watt/dummy-golang-project:latest
    deploy:
      restart_policy:
        condition: any
      labels:
        traefik.port: "9999"
    ports:
    - 9999:9999

  dummy-nodejs-project:
    container_name: dummy-nodejs-project
    image: rms1000watt/dummy-nodejs-project:latest
    deploy:
      restart_policy:
        condition: any
      labels:
        traefik.port: "3000"
    ports:
    - 3000:3000

  portainer:
    container_name: portainer
    image: portainer/portainer
    deploy:
      placement:
        constraints: 
        - node.role == manager
      restart_policy:
        condition: any
      labels:
        traefik.port: "9000"
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer-data:/data

  traefik:
    container_name: traefik
    command: --logLevel=DEBUG --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web
    image: traefik:v1.4.6-alpine
    privileged: true
    deploy:
      placement:
        constraints: 
        - node.role == manager
      restart_policy:
        condition: any
    ports:
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  